#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - nginx

# Дополнительные команды после установки пакетов
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - echo "<h1>Welcome to ${project_name} VM</h1>" | sudo tee /var/www/html/index.html

